### PR TITLE
Major Cleanup and Refactor

### PR DESCRIPTION
**Pull request by SoulSeekkor**
First off thank you @porkserver !  I am no C++ expert so I was attempting to fix this module for a small group of us that wanted to use it and only made minor progress.  Once you fixed the bulk of it I was able to attempt to revamp some things with it.  I'll try to summarize what I've done, this is from the "Final Cleanup" commit, but would invalidate the two commits you've done since anyway.

- Complete rename and refactor of code to match commands and purpose more clearly.
- Added new poisons vendor for purchase.
- Added new neutral auctioneer for purchase.
- Replaced existing profession trainers with neutral trainers as the existing were Scryer only.
- Added new portal game objects to be used and updated their position to be more useful.
- Added new orientation column to the guild house table and updated the existing coordinates, giving a much better teleport to guild house experience.
- Updated to allow all guild members to purchase by default, and added a new setting that only allows the guild master to sell the guild house by default.
- Removed the custom and broken NPCs that did nothing at all including the Food & Drink and Ammo & Repair vendor.  This has been replaced with vendors that actually do something.
- Repositioned all existing vendors to make more sense.
- Fixed deprecated warnings for the commands builder.
- Cleaned up a lot of the SQL.
- Removed weird new NPC for death knight when the existing one works just fine.

Things to do:
- Selling the guild house does not actually remove any of the creatures/objects.
- Need to change all profession trainers to the Dalaran ones, but those are broken and only teach grand master and above currently.
- Add a cooking fire purchaseable.

### CODE REVIEW

**Comment by porkserver** [comment]
This is great.  Let me grab this and see how it plays on my server.  I am very new to C++ and have been getting a lot of help along the way.  I had been focusing on getting the existing setup working but had similar ideas to move things around.  It looks like you were able to address things I have been working on/struggling with.  I'll post up soon!

**Comment by SoulSeekkor** [comment]
Sounds good!  Out of curiosity where were you getting help?  Yeah you took care of the part I was struggling with so I could focus on the other things, assuming I did them correctly lol.  Noticed the guild_house table shouldn't even be there for world, you'll want to start fresh or remove that table and update the guild_house table in the character database (for the new orientation column and updated coordinates).

I look forward to your feedback!

**Comment by porkserver** [comment]
Yeah my versions of the sql are much different as well.  but were a work in progress.  a 2nd set of eyes is great!

I was working with folks in the AC discord.

**Comment by SoulSeekkor** [comment]
Awesome, yeah I need to jump in there!  As a side note, the portal objects I snagged from here:
https://github.com/azerothcore/portals-in-all-capitals

Of course I added two new ones to that and possibly tweaked the rest, I'll be doing a pull request to that once I've added the additional portals to each capital city.

**Comment by SoulSeekkor** [comment]
Oh, also need to figure out how to make the GM Island area a rested area, that's highest on my list.

**Comment by porkserver** [comment]
Causes core crash on starter portal.  Checking code.
Was a little confused by all the new npc ID's, I had to do some reworking on my server to get things back up.

**Comment by porkserver** [comment]
My crash report,  it's crashing on Gameobject spawn and placement.  Not sure about the purpose of adding the orientation field to guild_house.  I'm going to look at your chat handler functions and try to integrate that.  I think adding the extra bells and whistles at this time is a bit premature.  My goal is to get things to a working product as it was originally built.  Once It is clearing build tests I do want to add some of these changes which were already on my roadmap.

[gdb.txt](https://github.com/porkserver/mod_guildhouse/files/8403512/gdb.txt)

**Comment by SoulSeekkor** [comment]
Sorry yeah, I changed a lot of the IDs to avoid conflicts and make them similar ranges to the portals.  You may need to remove the 'build' directory, recreate, and build fresh (for me it really doesn't like when you change the file names for things you have build previously and removed files which no longer exist, both of which I've done to clean up the filenames some).

You want the orientation field for guild_house as that determines the direction your character faces when you teleport to it, it used to use whatever your current orientation was which didn't make much sense so you'd teleport and be facing random directions.

It should work with the latest core code, as long as you remove that 'build' folder, run the cmake and build commands again and boom!  I'm running this on Ubuntu 20.04.

**Comment by porkserver** [comment]
This was a clean build on core commit from 9 hours ago,  going to spin up a fresh PTR with just this PR and try again.

**Comment by porkserver** [comment]
Compiling now.  I cloned your branch directly I started getting git errors complaining of a conflict, which made no sense.  I was working in brand new clone folders and locations :|

**Comment by SoulSeekkor** [comment]
Hmm yeah you shouldn't be able to get a git conflict with a fresh folder, you removed the mod_guildhouse folder if there was an existing one correct?  My repo is 2 commits and quite a few ahead of yours so if you have yours there it will cause a conflict.  I'd be happy to add you on Discord if that would help as well.

**Comment by porkserver** [comment]
Well done.  - Clean build and everything is working as intended!
(I hate your new portal locations, but I also hated the previous ones.)
I was quite partial to the bookshelves for the trainers personally, I found once you add a bunch of stuff to the house NPC's can really clutter things up.  Honestly though this is a great base for people to start with!  I am going to play with this and fill up a guild house, make some more, delete some using the different methods and look at DB changes.  Removal of the house creature and object entries was terribly broken.

I think I botched the first build making the DB changes.

**Comment by SoulSeekkor** [comment]
Funny you mentioned that, one of my buddies and I were partial to the bookshelves as well lol!  But to do so we'll need to create all new NPCs and use that for the display model, I did have that on the list of things to do but forgot to add that.  Ideally they would ALL be new NPCs, as the food & drink for example is missing the LOW level food and drink items, but this was kind of the best I could do without entirely new NPCs and even more SQL fun.  Just wanted it to function for us so we could finally use it. :)

Glad you got it working!  I think between the two of us we'll have a sweet viable module, hopefully we can get it merged into the main repo!  I'm not done with it, just needed a little break as everything is leveling past me and I wanted to catch up a little lol!

**Comment by porkserver** [comment]
Merging to master - integrating planned fixes by [SoulSeekkor]
Will update roadmap with new additional ideas
#ExtraHands!

**Comment by porkserver** [comment]
DIscord - Nelnamara #8596

**Pull request merged**
